name: MacOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-gradle-project:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '19'
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle build and test
        run: ./gradlew build test
      - name: Create package using jlink
        run: ./gradlew jlink jpackage
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IsoParser-MacOS_x64
          path: build/jpackage/*.dmg
